### ISSUE TITLE
Set different values for resource requests/limits for NFS resources

### ISSUE THREAD

**Issue by kingnarmer** [hpe-storage/truenas-csp#50]
I'm encountering issues with NFS resources pre-allocating excessive CPU and memory in my Kubernetes cluster. For instance, I have several NFS mounts: most of NFS pods consume around 200Mi CPU and 150MiB memory, but two NFS pods are pre-allocated 1 CPU and 2GB. The default for resource/limit values are set at nfsResourceLimitsMemoryMi (2GiB) and nfsResourceLimitsCpuM (1 CPU).

How can I configure different values for NFS resource requests and limits? Currently, the same value is set for both, leading to resource over-allocation and potential CPU throttling for other workloads. Any advice would be appreciated. Thanks!

**Comment by datamattsson** [comment]
> How to configure nfsResource request to be different from resource limits ?

Yes, the base StorageClass parameters applicable to all CSPs using the HPE CSI Driver can [be found here](https://scod.hpedev.io/csi_driver/using.html#base_storageclass_parameters).

What you're looking for is `nfsResourceLimitsCpuM` and `nfsResourceLimitsMemoryMi`.

**Comment by kingnarmer** [comment]
I saw the nfsResourceLimitsCpuM/nfsResourceLimitsCpuM. I am looking for how to configure the requests to be different from limits. Setting both to same value causes cluster to over allocate resources .Most of nfs pods uses low resources while two uses high resources.

**Comment by datamattsson** [comment]
Ok, I see what you're saying now and I somehow mixed this up with your other question. I'm not sure why this was left out in the implementation to be quite honest, it's clearly not complete without requests and obviously has impacts on systems with scarce resources.

I can file a JIRA with HPE because that's clearly where the change need to come from. If you're handy with golang you can add the necessary stanzas here in the meantime: https://github.com/hpe-storage/csi-driver/blob/8874fe968539c6f42c2d7fa6eccd52b584cdf0a8/pkg/flavor/kubernetes/nfs.go#L489 (or easier, remove the resource limit code and add defaults in a LimitRange that is applied on the Namespace).

**Comment by kingnarmer** [comment]
I appreciate if you file ticket with HPE. I can file one on HPE github if this helps.

**Comment by kingnarmer** [comment]
I opened issue with HPE on github. 

https://github.com/hpe-storage/csi-driver/issues/366

**Comment by datamattsson** [comment]
Fixed in https://github.com/hpe-storage/csi-driver/pull/397
